name: Shared Setup
description: "Cache Cargo registry and build"

inputs:
  cache_key_suffix:
    description: "Suffix to append to the cache key"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Rust
      run: rustup update stable
      shell: bash
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-${{ inputs.cache_key_suffix }}-
    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-${{ inputs.cache_key_suffix }}-
